import { Manrope } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import { Provider } from "@/components/ui/provider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const generalSans = localFont({
  src: './GeneralSans-Medium.woff2',
  variable: "--font-general-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Masters Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${generalSans.variable} antialiased `}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
